# General configuration
output = "tokens_output.pdf"
verbose = true
system = "D&D 5e"

# Paper settings
paper_size = "A4"
orientation = "portrait"
margin = 0.1

# Layout settings
rotation = true

# Monster configurations
[monsters.goblin]
name = "Goblin"
size = "Small"
type = "Humanoid"
image_url = "https://picsum.photos/200"
thumbnail_url = "https://picsum.photos/50"
tokens = [
    { type = "circle", size = "medium", count = 33},
    { type = "circle", count = 2},
]

[monsters.orc]
name = "Orc"
size = "Medium"
type = "Humanoid"
image_url = "https://picsum.photos/300"
thumbnail_url = "https://picsum.photos/75"
tokens = [
    { type = "circle", size = "large", count = 1},
    { type = "circle", size = "huge", count = 1},
]