# General configuration
output = "tokens_output.pdf"
verbose = true

# Paper settings
paper_size = "A4"
orientation = "portrait"
margin = 10

# Tokens configuration
[[tokens]]
type = "circle"
radius = 30
color = "blue"
border_color = "black"
border_width = 2

[[tokens]]
type = "circle"
radius = 60
color = "green"
border_color = "yellow"
border_width = 3

[[tokens]]
type = "circle"
image_url = "https://picsum.photos/200"
width = 50
height = 50

[[tokens]]
type = "circle"
image_url = "https://picsum.photos/200/300"
width = 100
height = 100
border_color = "red"
border_width = 1
